#!/usr/bin/env bash
set -euo pipefail

log_info() { printf '[INFO] %s\n' "$*"; }
log_warn() { printf '[WARN] %s\n' "$*" >&2; }
log_error() { printf '[ERROR] %s\n' "$*" >&2; }

require_var() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    log_error "Missing required variable: ${name}"
    exit 1
  fi
}

require_bool() {
  local name="$1"
  local value="${!name:-}"
  if [[ "$value" != "true" && "$value" != "false" ]]; then
    log_error "${name} must be true or false."
    exit 1
  fi
}

run_apt_get_ipv4() {
  local attempt=1
  local max_attempts=10

  while true; do
    if apt-get -o DPkg::Lock::Timeout=300 -o Acquire::ForceIPv4=true "$@"; then
      return
    fi

    if (( attempt >= max_attempts )); then
      log_error "apt-get failed after ${max_attempts} attempts: apt-get $*"
      exit 1
    fi

    log_warn "apt-get is busy or failed; retrying in 5 seconds (attempt ${attempt}/${max_attempts})."
    attempt=$(( attempt + 1 ))
    sleep 5
  done
}

apt_update_ipv4() {
  run_apt_get_ipv4 update -y
}

apt_install_ipv4() {
  DEBIAN_FRONTEND=noninteractive run_apt_get_ipv4 install -y "$@"
}

package_installed() {
  dpkg -s "$1" >/dev/null 2>&1
}

install_packages_if_missing() {
  local missing=()
  local pkg

  for pkg in "$@"; do
    if ! package_installed "$pkg"; then
      missing+=("$pkg")
    fi
  done

  if (( ${#missing[@]} == 0 )); then
    log_info "Required packages already installed: $*"
    return
  fi

  apt_update_ipv4
  apt_install_ipv4 "${missing[@]}"
}

node_major_version() {
  if ! command -v node >/dev/null 2>&1; then
    return 1
  fi

  node -v | sed -E 's/^v([0-9]+).*/\1/'
}

ensure_nodesource_repo() {
  local major="$1"
  local keyring="/etc/apt/keyrings/nodesource.gpg"
  local list_file="/etc/apt/sources.list.d/nodesource.list"
  local list_line="deb [signed-by=${keyring}] https://deb.nodesource.com/node_${major}.x nodistro main"

  install_packages_if_missing ca-certificates curl gnupg

  install -d -m 0755 /etc/apt/keyrings
  if [[ ! -f "$keyring" ]]; then
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o "$keyring"
    chmod 0644 "$keyring"
  fi

  if [[ ! -f "$list_file" ]] || ! grep -Fq "$list_line" "$list_file"; then
    printf '%s\n' "$list_line" > "$list_file"
  fi
}

install_node_if_needed() {
  local required_major="$1"
  local current_major=""

  if current_major="$(node_major_version)"; then
    if (( current_major >= required_major )); then
      log_info "Node ${current_major} detected (meets >= ${required_major})."
      return
    fi
    log_warn "Node ${current_major} detected, upgrading to ${required_major}+"
  fi

  ensure_nodesource_repo "$required_major"
  apt_update_ipv4
  apt_install_ipv4 nodejs
  log_info "Node installation complete: $(node -v)"
}

install_pnpm_if_requested() {
  if [[ "${INSTALL_PNPM}" != "true" ]]; then
    return
  fi

  if command -v pnpm >/dev/null 2>&1; then
    log_info "pnpm already installed."
    return
  fi

  if ! command -v corepack >/dev/null 2>&1; then
    log_error "corepack is unavailable; cannot install pnpm automatically."
    exit 1
  fi

  corepack enable
  corepack prepare pnpm@latest --activate
  log_info "pnpm installed via corepack."
}

ensure_openclaw_user_and_dir() {
  if [[ "${CREATE_OPENCLAW_USER}" == "true" ]]; then
    if ! id -u "${OPENCLAW_SETUP_USER}" >/dev/null 2>&1; then
      useradd --create-home --shell /bin/bash "${OPENCLAW_SETUP_USER}"
      log_info "Created user ${OPENCLAW_SETUP_USER}."
    fi
  fi

  mkdir -p "${OPENCLAW_SETUP_DIR}"
  if id -u "${OPENCLAW_SETUP_USER}" >/dev/null 2>&1; then
    chown -R "${OPENCLAW_SETUP_USER}:${OPENCLAW_SETUP_USER}" "${OPENCLAW_SETUP_DIR}"
  fi
}

write_next_step_hints() {
  local bind_ip
  bind_ip="${OPENCLAW_BIND_IP:-${WG_VPS_IP%%/*}}"
  local hint_file="${OPENCLAW_SETUP_DIR}/openclaw-host-setup.env"
  local tmp_file
  tmp_file="$(mktemp)"

  {
    echo "# Generated by OnboardingVPSOpenClaw"
    echo "# This file is informational and safe to edit."
    echo "OPENCLAW_BIND_IP=${bind_ip}"
    echo "OPENCLAW_PORT=${OPENCLAW_PORT}"
    echo "OPENCLAW_SETUP_USER=${OPENCLAW_SETUP_USER}"
    echo "OPENCLAW_SETUP_DIR=${OPENCLAW_SETUP_DIR}"
  } > "$tmp_file"

  install -m 0644 "$tmp_file" "$hint_file"
  rm -f "$tmp_file"
  log_info "Wrote host setup hints: ${hint_file}"
}

if [[ $EUID -ne 0 ]]; then
  log_error "This module must run as root."
  exit 1
fi

CONFIG_FILE="${1:-}"
if [[ -z "$CONFIG_FILE" || ! -f "$CONFIG_FILE" ]]; then
  log_error "Usage: $0 /absolute/path/to/config.env"
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "$CONFIG_FILE"
set +a

OPENCLAW_SETUP_DIR="${OPENCLAW_SETUP_DIR:-/opt/openclaw}"
OPENCLAW_SETUP_USER="${OPENCLAW_SETUP_USER:-openclaw}"
CREATE_OPENCLAW_USER="${CREATE_OPENCLAW_USER:-true}"
INSTALL_NODEJS="${INSTALL_NODEJS:-true}"
NODEJS_MAJOR_VERSION="${NODEJS_MAJOR_VERSION:-25}"
INSTALL_PNPM="${INSTALL_PNPM:-false}"

require_var OPENCLAW_PORT
require_var WG_VPS_IP
require_var OPENCLAW_SETUP_DIR
require_var OPENCLAW_SETUP_USER
require_var CREATE_OPENCLAW_USER
require_var INSTALL_NODEJS
require_var NODEJS_MAJOR_VERSION
require_var INSTALL_PNPM
require_bool CREATE_OPENCLAW_USER
require_bool INSTALL_NODEJS
require_bool INSTALL_PNPM

if [[ ! "${OPENCLAW_PORT}" =~ ^[0-9]+$ ]] || (( OPENCLAW_PORT < 1 || OPENCLAW_PORT > 65535 )); then
  log_error "Invalid OPENCLAW_PORT: ${OPENCLAW_PORT}"
  exit 1
fi
if [[ ! "${NODEJS_MAJOR_VERSION}" =~ ^[0-9]+$ ]] || (( NODEJS_MAJOR_VERSION < 18 )); then
  log_error "Invalid NODEJS_MAJOR_VERSION: ${NODEJS_MAJOR_VERSION}"
  exit 1
fi

log_info "Installing baseline host packages."
install_packages_if_missing ca-certificates curl git jq unzip

if [[ "${INSTALL_NODEJS}" == "true" ]]; then
  install_node_if_needed "${NODEJS_MAJOR_VERSION}"
fi

install_pnpm_if_requested
ensure_openclaw_user_and_dir
write_next_step_hints

log_info "Host preparation completed. OpenClaw was not installed by this script."
